version: 2
jobs:
  build:
    docker:
      - image: node:16.13.0
        auth:
          username: $DOCKERHUB_USR
          password: $DOCKERHUB_PWD
    steps:
      - checkout
      - run:
          name: Node Packages Download
          command: npm install
      - run:
          name: Project Build
          command: npm run build
      - run:
          name: Node CI Packages Download (No optionals)
          command: cd ./build && npm ci --production --no-optional
      - add_ssh_keys
      - run:
          name: Generate Artifact
          command: |
            apt-get update && apt-get -y install rsync
            mkdir /tmp/artifacts
            tar -czf /tmp/build.tar.gz ./build
            ssh-keyscan -H 155.138.227.209 >> ~/.ssh/known_hosts
            rsync -va --delete /tmp/build.tar.gz root@155.138.227.209:/root/circleci-folder
            ssh root@155.138.227.209 <<'ENDSSH'
            cd /root/circleci-folder
            tar -xf build.tar.gz
            pm2 stop 0
            pm2 start 0
            ENDSSH
      - store_artifacts:
          path: /tmp/build.tar.gz
          destination: artifact-file
