version: 2
jobs:
  build:
    docker:
      - image: node:16.13.0
        auth:
          username: $DOCKERHUB_USR
          password: $DOCKERHUB_PWD
    steps:
      - checkout
      - run: npm install
      - run: npm run build
